analytics: {}
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.428007
  lightness: 0.754779
  rhythmicContrast: 0.698308
  saturation: 0.729045
cta: {}
layout_spectrum: 0.993243
name: TincherWorld
opengraph: {}
purpose: []
typography_spectrum: 0.709459
