name: TincherWorld
favicon: null
layout_spectrum: 0.8410955746658146
typography_spectrum: 0.09824283933266997
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4280072443652898
  lightness: 0.7547798573505133
  saturation: 0.7290454446338117
  rhythmicContrast: 0.6983086366672069
purpose: []
